[2020-03-03 11:17:09,456]-[INFO]-[log_module.py-test_log]-[日志信息]:正在执行login模块6条用例，测试数据是{'mobilephone':'13541781424','pwd':'123456'}
[2020-03-03 11:17:09,885]-[INFO]-[log_module.py-test_log]-[日志信息]:实际结果是{"status":1,"code":"10001","data":null,"msg":"登录成功"}，测试结果是：PASS
[2020-03-03 11:17:09,892]-[INFO]-[log_module.py-test_log]-[日志信息]:正在执行login模块7条用例，测试数据是{'mobilephone':'','pwd':'123456'}
[2020-03-03 11:17:10,615]-[INFO]-[log_module.py-test_log]-[日志信息]:实际结果是{"status":0,"code":"20103","data":null,"msg":"手机号不能为空"}，测试结果是：PASS
[2020-03-03 11:17:10,621]-[INFO]-[log_module.py-test_log]-[日志信息]:正在执行login模块8条用例，测试数据是{'mobilephone':'13541781424','pwd':''}
[2020-03-03 11:17:10,915]-[INFO]-[log_module.py-test_log]-[日志信息]:实际结果是{"status":0,"code":"20103","data":null,"msg":"密码不能为空"}，测试结果是：PASS
[2020-03-03 11:17:10,920]-[INFO]-[log_module.py-test_log]-[日志信息]:正在执行login模块9条用例，测试数据是{'mobilephone':'13541781424','pwd':'1234567'}
[2020-03-03 11:17:11,355]-[INFO]-[log_module.py-test_log]-[日志信息]:实际结果是{"status":0,"code":"20111","data":null,"msg":"用户名或密码错误"}，测试结果是：PASS
[2020-03-03 11:17:11,359]-[INFO]-[log_module.py-test_log]-[日志信息]:正在执行login模块10条用例，测试数据是{'mobilephone':'18296208190','pwd':'123456'}
[2020-03-03 11:17:11,798]-[INFO]-[log_module.py-test_log]-[日志信息]:实际结果是{"status":0,"code":"20111","data":null,"msg":"用户名或密码错误"}，测试结果是：PASS
